version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-ubuntu
    ports:
      - "6969:6969"
    volumes:
      - ./graphs:/app/graphs
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=