version: "3.7"
services:
  apihub:
    image: apihub
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apihub
    ports:
      - "6969:6969"
    volumes:
      - /home/administrator/docker/apihub/API-HUB/docker_conf/config.json:/app/config.json
      - /home/administrator/docker/apihub/API-HUB/docker_conf/graphs:/app/graphs
    restart: unless-stopped
