version: "3.7"
services:
  apihub:
    image: apihub
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    volumes:
      - "${PWD}"/docker_conf/config.json:/app/config.json
      - "${PWD}"/docker_conf/graphs:/app/graphs
    restart: unless-stopped
