# Use the Python 3.7.4 Alpine base image
FROM python:3.7.4-alpine3.10

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Create and activate a virtual environment
RUN python3 -m venv venv
RUN source venv/bin/activate

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Make port 6969 available to the world outside this container
EXPOSE 6969

# Run app.py when the container launches
CMD ["python", "app.py"]